// Code generated by mockery v2.14.0. DO NOT EDIT.

package products

import mock "github.com/stretchr/testify/mock"

// MockNotifier is an autogenerated mock type for the Notifier type
type MockNotifier struct {
	mock.Mock
}

// NotifyError provides a mock function with given fields: message
func (_m *MockNotifier) NotifyError(message string) {
	_m.Called(message)
}

type mockConstructorTestingTNewMockNotifier interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockNotifier creates a new instance of MockNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockNotifier(t mockConstructorTestingTNewMockNotifier) *MockNotifier {
	mock := &MockNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
