// Code generated by mockery v2.14.0. DO NOT EDIT.

package products

import mock "github.com/stretchr/testify/mock"

// MockDatabase is an autogenerated mock type for the Database type
type MockDatabase struct {
	mock.Mock
}

// GetProductById provides a mock function with given fields: id
func (_m *MockDatabase) GetProductById(id string) (Product, error) {
	ret := _m.Called(id)

	var r0 Product
	if rf, ok := ret.Get(0).(func(string) Product); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewMockDatabase interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockDatabase creates a new instance of MockDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockDatabase(t mockConstructorTestingTNewMockDatabase) *MockDatabase {
	mock := &MockDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
